export const SERVER_URL = 'http://localhost:8888'

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS'
export const DEL_DATA_SUCCESS = 'DEL_DATA_SUCCESS'
export const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS'

export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
