export const SERVER_URL = 'http://localhost:5000';

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';

export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
