export const FETCH_PASSWORD = 'FETCH_PASSWORD';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const DELETE_PASSWORD = 'DELETE_PASSWORD';
export const SEARCH_PASSWORD ='SEARCH_PASSWORD';
export const EDIT_PASSWORD ='EDIT_PASSWORD';
